# Generated by Django 3.1.7 on 2021-05-11 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('release_date', models.DateField(null=True)),
                ('console_platforms', models.ManyToManyField(to='contentConsumed.ConsolePlatform')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_platforms', models.ManyToManyField(to='contentConsumed.ConsolePlatform')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentConsumed.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
