# Generated by Django 3.1.7 on 2021-04-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentConsumed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
