# Generated by Django 3.1.7 on 2021-05-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentConsumed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleplatform',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consoleplatform',
            name='tag_color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
