# Generated by Django 3.1.7 on 2021-04-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentConsumed', '0002_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
