# Generated by Django 3.1.7 on 2021-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentConsumed', '0003_auto_20210421_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
