# Generated by Django 3.1.7 on 2021-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentConsumed', '0005_ownedgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolePlatforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Platforms',
            field=models.ManyToManyField(to='contentConsumed.ConsolePlatforms'),
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='platforms',
            field=models.ManyToManyField(to='contentConsumed.ConsolePlatforms'),
        ),
    ]
