# Generated by Django 3.1.7 on 2021-05-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentConsumed', '0006_auto_20210506_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Platforms',
            new_name='console_platforms',
        ),
        migrations.RenameField(
            model_name='ownedgame',
            old_name='platforms',
            new_name='console_platforms',
        ),
    ]
