# Generated by Django 3.2.5 on 2021-08-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=4)),
                ('last_activity', models.DateTimeField(null=True)),
            ],
        ),
    ]
